FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM caddy:2-alpine

COPY Caddyfile.prod /etc/caddy/Caddyfile
COPY --from=build /app/dist/client /srv

EXPOSE 3000
