/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmartControlRouteImport } from './routes/smart-control'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrderRouteImport } from './routes/order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientTrackRouteImport } from './routes/client.track'
import { Route as ClientSmartControlRouteImport } from './routes/client.smart-control'
import { Route as ClientOrdersRouteImport } from './routes/client.orders'
import { Route as ClientNotificationsRouteImport } from './routes/client.notifications'
import { Route as ClientAccountRouteImport } from './routes/client.account'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'

const SmartControlRoute = SmartControlRouteImport.update({
  id: '/smart-control',
  path: '/smart-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTrackRoute = ClientTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => ClientRoute,
} as any)
const ClientSmartControlRoute = ClientSmartControlRouteImport.update({
  id: '/smart-control',
  path: '/smart-control',
  getParentRoute: () => ClientRoute,
} as any)
const ClientOrdersRoute = ClientOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ClientRoute,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAccountRoute = ClientAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ClientRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/smart-control': typeof SmartControlRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/account': typeof ClientAccountRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/orders': typeof ClientOrdersRoute
  '/client/smart-control': typeof ClientSmartControlRoute
  '/client/track': typeof ClientTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/smart-control': typeof SmartControlRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/account': typeof ClientAccountRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/orders': typeof ClientOrdersRoute
  '/client/smart-control': typeof ClientSmartControlRoute
  '/client/track': typeof ClientTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/products': typeof ProductsRoute
  '/services': typeof ServicesRoute
  '/smart-control': typeof SmartControlRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/account': typeof ClientAccountRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/orders': typeof ClientOrdersRoute
  '/client/smart-control': typeof ClientSmartControlRoute
  '/client/track': typeof ClientTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/client'
    | '/contact'
    | '/order'
    | '/products'
    | '/services'
    | '/smart-control'
    | '/admin/clients'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/services'
    | '/admin/settings'
    | '/client/account'
    | '/client/notifications'
    | '/client/orders'
    | '/client/smart-control'
    | '/client/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/client'
    | '/contact'
    | '/order'
    | '/products'
    | '/services'
    | '/smart-control'
    | '/admin/clients'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/services'
    | '/admin/settings'
    | '/client/account'
    | '/client/notifications'
    | '/client/orders'
    | '/client/smart-control'
    | '/client/track'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/client'
    | '/contact'
    | '/order'
    | '/products'
    | '/services'
    | '/smart-control'
    | '/admin/clients'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/services'
    | '/admin/settings'
    | '/client/account'
    | '/client/notifications'
    | '/client/orders'
    | '/client/smart-control'
    | '/client/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClientRoute: typeof ClientRouteWithChildren
  ContactRoute: typeof ContactRoute
  OrderRoute: typeof OrderRoute
  ProductsRoute: typeof ProductsRoute
  ServicesRoute: typeof ServicesRoute
  SmartControlRoute: typeof SmartControlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/smart-control': {
      id: '/smart-control'
      path: '/smart-control'
      fullPath: '/smart-control'
      preLoaderRoute: typeof SmartControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/track': {
      id: '/client/track'
      path: '/track'
      fullPath: '/client/track'
      preLoaderRoute: typeof ClientTrackRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/smart-control': {
      id: '/client/smart-control'
      path: '/smart-control'
      fullPath: '/client/smart-control'
      preLoaderRoute: typeof ClientSmartControlRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/orders': {
      id: '/client/orders'
      path: '/orders'
      fullPath: '/client/orders'
      preLoaderRoute: typeof ClientOrdersRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/account': {
      id: '/client/account'
      path: '/account'
      fullPath: '/client/account'
      preLoaderRoute: typeof ClientAccountRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientAccountRoute: typeof ClientAccountRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientOrdersRoute: typeof ClientOrdersRoute
  ClientSmartControlRoute: typeof ClientSmartControlRoute
  ClientTrackRoute: typeof ClientTrackRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAccountRoute: ClientAccountRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientOrdersRoute: ClientOrdersRoute,
  ClientSmartControlRoute: ClientSmartControlRoute,
  ClientTrackRoute: ClientTrackRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ClientRoute: ClientRouteWithChildren,
  ContactRoute: ContactRoute,
  OrderRoute: OrderRoute,
  ProductsRoute: ProductsRoute,
  ServicesRoute: ServicesRoute,
  SmartControlRoute: SmartControlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
